# Generated by Django 4.2 on 2023-04-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=250, verbose_name='Url amigable')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('visible', models.BooleanField(verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
    ]
