# Generated by Django 4.2 on 2023-04-20 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=250, unique=True, verbose_name='Url amigable'),
        ),
    ]
